apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: noobernetes
spec:
  template:
    metadata:
      name: noobernetes
      labels:
        service: noobernetes-service
    spec:
      containers:
      - name: noobernetes-container
        image: noobernetes:hello-world
        resources:
          requests:
            cpu: 200m
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SUPER_SECRET
          value: "This is my secret string"
      restartPolicy: Always
