apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: noobernetes-sinatra
spec:
  template:
    metadata:
      name: noobernetes-sinatra
      labels:
        service: noobernetes-sinatra
    spec:
      containers:
      - name: noobernetes-sinatra-container
        image: noobernetes-sinatra:latest
        resources:
          requests:
            cpu: 200m
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SUPER_SECRET
          value: "This is my secret string"
      restartPolicy: Always
