apiVersion: v1
kind: Service
metadata:
  labels:
    service: noobernetes-sinatra
  name: noobernetes-sinatra-service
spec:
  type: NodePort
  ports:
  - name: noobernetes-sinatra-port
    port: 4000
    protocol: TCP
    targetPort: 4567
    nodePort: 30000
  selector:
    service: noobernetes-sinatra
    