apiVersion: v1
kind: Service
metadata:
  name: noobernetes
  labels:
    service: noobernetes-service
spec:
  type: NodePort
  ports:
  - name: noobernetes-port
    port: 4000
    protocol: TCP
    targetPort: 4567
    nodePort: 30000
  selector:
    service: noobernetes-service
